server:
  port: 8080
  servlet:
    context-path: /api
spring:
  # Database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:coffee_shops}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  # JPA configuration
  jpa:
    # PotGIS configuration
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql