# Use postgres/postgres user/password credentials
version: '3.1'

services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8050:8080